#!/usr/bin/env bash
# Information about domains owner
sub_domains()
{
    register=$(dig "$i"."$1" | awk '/ANSWER SECTION:/ {getline; print $4}')
    ip=$(dig "$i"."$1" | awk '/ANSWER SECTION:/ {getline; print $5}')
}
if [ -z "$2" ]; then
    for i in "www" "lb-01" "web-01" "web-02"; do
	sub_domains "$1"
	echo "The subdomain $i is a $register record and points to $ip"
    done
else
    i="$2"
    sub_domains "$1"
    echo "The subdomain $i is a $register record and points to $ip"
fi
