#!/usr/bin/env bash
# Information about domains owner
LIST=( "www" "lb-01" "web-01" "web-02" )
sub_domains(){
    echo -n "The subdomain $2 "
    dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | grep -v 'ANSWER SECTION:' | awk '{print "is a", $4, "record and points to", $5}'
}
if [ $# -eq 2 ]; then
    sub_domains "$1" "$2"
else
    for i in "${LIST[@]}" ; do
        sub_domains "$1" "$i"
    done
fi
