#!/usr/bin/env bash
# redirect_me to youtube
# bash script that configure your Nginx server so that /redirect_me is redirecting to another page
REDIR="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n" 
SRC="/etc/nginx/sites-available/default" 
apt-get -y update 
apt-get -y install nginx 
sudo service nginx start 
echo "Holberton School" | sudo tee /var/www/html/index.html 
sudo sed -i "30i $REDIR" $SRC 
sudo service nginx restart
