#!/usr/bin/env bash
# install nginx to create html pages - 404 

apt-get -y update 
apt-get -y install nginx 
sudo service nginx start 
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak 
echo -e "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/404.html 
sudo sed -i 's|#error_page 404 \/404.html|error_page 404 \/404.html|' /etc/nginx/sites-available/default 
sudo service nginx start