#!/usr/bin/env bash
# install nginx to create html pages - 404 
REDIR="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n" 

SRC="/etc/nginx/sites-available/default" 
apt-get -y update 
apt-get -y install nginx 
sudo service nginx start 
echo "Holberton School" | sudo tee /var/www/html/index.html 
sudo sed -i "30i $REDIR" $SRC



#echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html 
#sudo sed -i "48i $ERRDIR" $SRC 
#sudo service nginx restart


sudo sed -i "s/#error_page 404/error_page 404/" /etc/nginx/sites-available/default 
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html 
sudo service nginx restart