#!/usr/bin/env bash
# install nginx to create html pages - 404 

apt-get -y update 
apt-get -y install nginx 
echo 'Holberton School' > /var/www/html/index.html 

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup 

REDI="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n" 
sed -i "37i\ $REDI" /etc/nginx/sites-available/default 
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html 
e404='/listen 80 default_server/a error_page 404 /404.html; location = /404.html {root /usr/share/nginx/html;\n internal;}' 
sed -i "$e404" /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server/a add_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-available/default
service nginx start
