#!/usr/bin/env bash
# install nginx to server

apt-get update
apt-get -y install nginx
sudo service nginx start

otherdefault="/etc/nginx/sites-available/default"
location="\\\tadd_header X-Served-By \$hostname;"
sudo sed -i "30i $location" "$otherdefault"
sudo service nginx restart
