#!/usr/bin/env bash
# install nginx to server

apt-get update
apt-get -y install nginx
sudo service nginx start

echo "Holberton School" > /var/www/html/index.html

otherdefault="/etc/nginx/sites-enabled/default"
location="\\\tadd_header X-Served-By \$hostname;"
sudo sed -i "30i $location" "$otherdefault"
sudo service nginx restart
