#!/usr/bin/env bash
# Creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ > /var/run/holbertonscript.pid

function f_sigterm {
    echo "I hate the kill command"
    sudo rm -R /var/run/holbertonscript.pid
    exit
}

function f_sigint {
    echo "Y U no love me?!"
    exit
}

function f_sigquit {
    sudo rm -R /var/run/holbertonscript.pid
    exit
}

trap f_sigterm SIGTERM
trap f_sigint SIGINT
trap f_sigquit SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done




# rm -R /var/run/holbertonscript.pid
