#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times
iterator=0
while ((iterator < 10))
do
  echo "Holberton School"
  let iterator=iterator+1
done
#while ((iterator > 0)); do echo Holberton School; iterator=$((iterator-1)); done
